GET http://localhost:8080/hello-path-variable/foo

###

POST http://localhost:8080/hello
Content-Type: application/json

{
    "message": "foo"
}

###

GET http://localhost:8080/hello-header
Content-Type: application/json
X-Name: Grzegorz


